project:
  type: website
  output-dir: docs

website:
  title: "qtm350-quiz02"
  navbar:
    left:
      - text: "Home"
        href: index.qmd 
      - text: "About"
        href: about.qmd 
      - text: "Life-GDP"
        href: life-gdp.qmd
      - text: "Life Population"
        href: life-population.qmd
      - text: "Country Analysis"
        href: country.qmd

format:
  html:
    theme: quartz
    css: styles.css
    toc: true




